# Generated by Django 3.0.2 on 2020-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cliente',
            field=models.CharField(choices=[('tech', 'Technical'), ('novel', 'Novel'), ('physco', 'Phsycological')], default='Navega', max_length=20),
        ),
    ]
