# Generated by Django 3.0.2 on 2020-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200124_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cliente',
            field=models.CharField(choices=[('tech', 'Technical'), ('novel', 'Novel'), ('physco', 'Phsycological')], default=0, max_length=20),
        ),
    ]
