# Generated by Django 3.0.2 on 2020-01-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200124_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['cliente', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.AddField(
            model_name='page',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
