# Generated by Django 3.0.2 on 2020-01-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200124_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title', 'client'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='precio',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='page',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url_pago',
        ),
        migrations.AddField(
            model_name='page',
            name='client',
            field=models.CharField(choices=[('navega_panama', 'Navega Panamá'), ('navega_rep_dom', 'Navega República Dominicana'), ('navega_guatemala', 'Navega Guatemala')], default=0, max_length=20, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.URLField(default=0, verbose_name='Link de pago'),
            preserve_default=False,
        ),
    ]
